"""3) თიოთეული მონაცემთა ტიპისთვის (str,int,float), შექმენით 5 ცვლადი და დაუწერეთ კომენტარი თუ რომელ მონაცემთა"
 ტიპს ინახავს ცვლადი"""

#(str) ტიპის ცვლადები
name = "ნატალი"     
city = "თბილისი"    
language = "Python"   
hobby = "ჭადრაკი"     
color = "ლურჯი"     

#(int) ტიპის ცვლადები
age = 15             # მთელი რიცხვი (integer)
year = 2009         # მთელი რიცხვი (integer)
temperature = 36.5     # მთელი რიცხვი (integer)
height_cm = 160      # მთელი რიცხვი (integer)
rapid_rating=1208         # მთელი რიცხვი (integer)

#(float) ტიპის ცვლადები
price = 19.99        # არამთლი რიცხვი (float)
weight = 72.5        # არამთელი რიცხვი (float)
pi = 3.14      # არამთელი რიცხვი (float)
distance_km = 12.8     # არამთელი რიცხვი (float)
speed = 55.6        # არამთელი რიცხვი (float)